{
  "language": "node_js",
  "sudo": true,
  "node_js": "v6.2.2",
  "install": "npm install",
  "cache": {
    "directories": null
  },
  "before_script": [
    "node_modules/protractor/bin/webdriver-manager start 2>&1 &",
    "sleep 5"
  ],
  "script": [
    "npm test"
  ],
  "after_success": null,
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}